/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bank.management.system.pkg1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.JLabel;

/**
 *
 * @author DAEZ
 */
public class LoggedPage extends javax.swing.JFrame {
    
    private String loggedInEmail; // Store the logged-in user's email
  

    // Constructor that accepts the labels
    public LoggedPage(JLabel lbl_Balance, JLabel lbl_WBalance, JLabel lbl_DBalance) {
        initComponents();  // Initialize components
        this.lbl_Balance = lbl_Balance;
        this.lbl_WBalance = lbl_WBalance;
        this.lbl_DBalance = lbl_DBalance;
        
        // Optionally, you can now access these labels in your methods and update them
    }

    // Method to update all balance labels
    private void updateBalanceLabels(double newBalance) {
        if (lbl_Balance != null) {
            lbl_Balance.setText(String.format("%.2f", newBalance));
        }
        if (lbl_WBalance != null) {
            lbl_WBalance.setText(String.format("%.2f", newBalance));
        }
        if (lbl_DBalance != null) {
            lbl_DBalance.setText(String.format("%.2f", newBalance));
        }
    }
    
    /**
     * Creates new form LoggedPage
     */
    public LoggedPage(String loggedInEmail) {
        initComponents();
        this.loggedInEmail = loggedInEmail; // Assign the logged-in email
        try {
        Connection();  // Initialize database connection
        
    } catch (SQLException ex) {
        Logger.getLogger(LoggedPage.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Database connection error: " + ex.getMessage());
    }
    }

    
    
    Connection con;
    Statement st;
    
    private static final String DbName = "bangko";
    private static final String DbDriver = "com.mysql.cj.jdbc.Driver";
    private static final String DbUrl = "jdbc:mysql://localhost:3306/"+DbName;
    private static final String DbUsername = "root";
    private static final String DbPassword = "";
    
    public void Connection() throws SQLException{
        try {
            Class.forName(DbDriver);
            con = (Connection) DriverManager.getConnection(DbUrl,DbUsername,DbPassword);
            st = con.createStatement();
            if (con!= null){
                System.out.print("Connection Successful");
            }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Head = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        WelcomePanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_Balance = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl_Name = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        DEPOSITPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_DBalance = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        btn_Deposit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_Deposit = new javax.swing.JTextField();
        WITHDRAWPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_WBalance = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        btn_Withdraw = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_Withdraw = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Head.setBackground(java.awt.Color.white);
        Head.setPreferredSize(new java.awt.Dimension(1280, 95));
        Head.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setText("BANGKO");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        Head.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/management/system/pkg1/BANGKO 40x40.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        Head.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel32.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/management/system/pkg1/Logout Butn.png"))); // NOI18N
        jLabel32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });
        Head.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 190, -1));

        jLabel33.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel33.setText("Withdraw");
        jLabel33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });
        Head.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, -1, -1));

        jLabel34.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel34.setText("Deposit");
        jLabel34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });
        Head.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 40, -1, -1));

        jLabel35.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel35.setText("Home");
        jLabel35.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel35MouseClicked(evt);
            }
        });
        Head.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, -1, -1));

        jPanel1.add(Head, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, -1));

        WelcomePanel.setBackground(java.awt.Color.white);

        jPanel5.setBackground(new java.awt.Color(248, 248, 248));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/management/system/pkg1/icons8_peso_symbol_80px.png"))); // NOI18N
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        lbl_Balance.setFont(new java.awt.Font("Poppins", 1, 72)); // NOI18N
        lbl_Balance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Balance.setText("250.00");
        jPanel5.add(lbl_Balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 100, 400, 78));

        jLabel12.setFont(new java.awt.Font("Poppins", 0, 53)); // NOI18N
        jLabel12.setText("Available Balance");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 488, 50));

        lbl_Name.setFont(new java.awt.Font("Poppins SemiBold", 0, 53)); // NOI18N
        lbl_Name.setText("Name");

        jLabel11.setFont(new java.awt.Font("Poppins", 0, 53)); // NOI18N
        jLabel11.setText("Welcome back,");

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/management/system/pkg1/WALLET.png"))); // NOI18N

        javax.swing.GroupLayout WelcomePanelLayout = new javax.swing.GroupLayout(WelcomePanel);
        WelcomePanel.setLayout(WelcomePanelLayout);
        WelcomePanelLayout.setHorizontalGroup(
            WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomePanelLayout.createSequentialGroup()
                .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WelcomePanelLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel39)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel40)
                        .addGap(334, 334, 334))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WelcomePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WelcomePanelLayout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WelcomePanelLayout.createSequentialGroup()
                                .addComponent(lbl_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)))))
                .addComponent(jLabel41)
                .addGap(175, 175, 175)
                .addComponent(jLabel38)
                .addGap(592, 592, 592))
            .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(WelcomePanelLayout.createSequentialGroup()
                    .addGap(109, 109, 109)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1562, Short.MAX_VALUE)))
        );
        WelcomePanelLayout.setVerticalGroup(
            WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomePanelLayout.createSequentialGroup()
                .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WelcomePanelLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel38))
                    .addGroup(WelcomePanelLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(lbl_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel39))
                    .addGroup(WelcomePanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel41)))
                .addGap(362, 362, 362))
            .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(WelcomePanelLayout.createSequentialGroup()
                    .addGap(169, 169, 169)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(841, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab1", WelcomePanel);

        DEPOSITPanel.setBackground(java.awt.Color.white);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/management/system/pkg1/DEPOSIT.png"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(250, 250, 250));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_DBalance.setBackground(new java.awt.Color(250, 250, 250));
        lbl_DBalance.setFont(new java.awt.Font("Poppins SemiBold", 0, 36)); // NOI18N
        lbl_DBalance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_DBalance.setText("P 1753.00");
        jPanel3.add(lbl_DBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 370, 40));

        jLabel21.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel21.setText("Current Balance");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 108, 169, -1));

        jLabel22.setFont(new java.awt.Font("Poppins SemiBold", 0, 36)); // NOI18N
        jLabel22.setText("DEPOSIT");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 187, 440, -1));

        jLabel23.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel23.setText("Please Enter Amount to Deposit");
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 290, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 440, -1));

        jButton3.setText("CANCEL");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 200, 50));

        btn_Deposit.setBackground(new java.awt.Color(255, 189, 16));
        btn_Deposit.setForeground(java.awt.Color.white);
        btn_Deposit.setText("DEPOSIT");
        btn_Deposit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_Deposit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DepositActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Deposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 200, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/management/system/pkg1/icons8_peso_symbol_60px.png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        txt_Deposit.setBackground(new java.awt.Color(250, 250, 250));
        txt_Deposit.setFont(new java.awt.Font("Poppins SemiBold", 0, 36)); // NOI18N
        txt_Deposit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Deposit.setText("0.0");
        txt_Deposit.setBorder(null);
        jPanel3.add(txt_Deposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 380, -1));

        javax.swing.GroupLayout DEPOSITPanelLayout = new javax.swing.GroupLayout(DEPOSITPanel);
        DEPOSITPanel.setLayout(DEPOSITPanelLayout);
        DEPOSITPanelLayout.setHorizontalGroup(
            DEPOSITPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DEPOSITPanelLayout.createSequentialGroup()
                .addGroup(DEPOSITPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DEPOSITPanelLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel17)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel36)
                        .addGap(334, 334, 334))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DEPOSITPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel37)
                .addGap(248, 248, 248)
                .addComponent(jLabel5)
                .addGap(592, 592, 592))
        );
        DEPOSITPanelLayout.setVerticalGroup(
            DEPOSITPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DEPOSITPanelLayout.createSequentialGroup()
                .addGroup(DEPOSITPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DEPOSITPanelLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel5))
                    .addGroup(DEPOSITPanelLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(DEPOSITPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DEPOSITPanelLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17))
                            .addComponent(jLabel37))))
                .addGap(365, 365, 365))
        );

        jTabbedPane1.addTab("tab1", DEPOSITPanel);

        WITHDRAWPanel.setBackground(java.awt.Color.white);
        WITHDRAWPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        WITHDRAWPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1706, 570, -1, -1));
        WITHDRAWPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 570, -1, -1));
        WITHDRAWPanel.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 564, -1, -1));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/management/system/pkg1/WITHDRAW.png"))); // NOI18N
        WITHDRAWPanel.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 660, -1));

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_WBalance.setBackground(new java.awt.Color(250, 250, 250));
        lbl_WBalance.setFont(new java.awt.Font("Poppins SemiBold", 0, 36)); // NOI18N
        lbl_WBalance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_WBalance.setText("P 1753.00");
        jPanel2.add(lbl_WBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 370, 40));

        jLabel13.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel13.setText("Available Balance");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 108, 169, -1));

        jLabel14.setFont(new java.awt.Font("Poppins SemiBold", 0, 36)); // NOI18N
        jLabel14.setText("Withdrawal");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 187, 440, -1));

        jLabel15.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel15.setText("Please Enter Amount to Withdraw");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 310, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 440, -1));

        jButton1.setText("CANCEL");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 200, 50));

        btn_Withdraw.setBackground(new java.awt.Color(255, 189, 16));
        btn_Withdraw.setForeground(java.awt.Color.white);
        btn_Withdraw.setText("WITHDRAW");
        btn_Withdraw.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_Withdraw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_WithdrawActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Withdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 200, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/management/system/pkg1/icons8_peso_symbol_60px.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        txt_Withdraw.setBackground(new java.awt.Color(250, 250, 250));
        txt_Withdraw.setFont(new java.awt.Font("Poppins SemiBold", 0, 36)); // NOI18N
        txt_Withdraw.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Withdraw.setText("0.0");
        txt_Withdraw.setBorder(null);
        jPanel2.add(txt_Withdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 380, -1));

        WITHDRAWPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 76, 520, 490));

        jTabbedPane1.addTab("tab1", WITHDRAWPanel);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        // TODO add your handling code here:
    
    int confirmed = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to log out?", 
            "Logout Confirmation", 
            JOptionPane.YES_NO_OPTION);
    
    
    if (confirmed == JOptionPane.YES_OPTION) {
       
        this.setVisible(false); 
        
        
        this.dispose();  
        
        
        MenuForm menuForm = new MenuForm();  
        menuForm.setVisible(true);  
    }
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jLabel33MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
        
    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel35MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_DepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DepositActionPerformed
        // TODO add your handling code here:
         // Pass the labels to the LoggedPage constructor
    
         try {
        String depositText = txt_Deposit.getText();
        if (depositText.isEmpty() || !depositText.matches("\\d+(\\.\\d{1,2})?")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid deposit amount.");
            return;
        }

        double depositAmount = Double.parseDouble(depositText);
        if (depositAmount <= 0) {
            JOptionPane.showMessageDialog(this, "Deposit amount must be greater than zero.");
            return;
        }

        String getBalanceQuery = "SELECT Balance FROM accountdetails WHERE Email = ?";
        try (PreparedStatement psGet = con.prepareStatement(getBalanceQuery)) {
            psGet.setString(1, loggedInEmail);

            ResultSet rs = psGet.executeQuery();
            if (rs.next()) {
                double currentBalance = rs.getDouble("Balance");
                double newBalance = currentBalance + depositAmount;

                String updateBalanceQuery = "UPDATE accountdetails SET Balance = ? WHERE Email = ?";
                try (PreparedStatement psUpdate = con.prepareStatement(updateBalanceQuery)) {
                    psUpdate.setDouble(1, newBalance);
                    psUpdate.setString(2, loggedInEmail);

                    psUpdate.executeUpdate();

                    // Update all balance labels
                    updateBalanceLabels(newBalance);

                    lbl_DBalance.setText(String.format("%.2f", newBalance));
                    txt_Deposit.setText("");

                    JOptionPane.showMessageDialog(this, "Deposit successful!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Account not found.");
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage());
    }
   
    }//GEN-LAST:event_btn_DepositActionPerformed

    private void btn_WithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_WithdrawActionPerformed
        // TODO add your handling code here:
        try {
        String withdrawText = txt_Withdraw.getText();  // Get the withdrawal amount from the text field
        if (withdrawText.isEmpty() || !withdrawText.matches("\\d+(\\.\\d{1,2})?")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid withdrawal amount.");
            return;
        }

        double withdrawAmount = Double.parseDouble(withdrawText);
        if (withdrawAmount <= 0) {
            JOptionPane.showMessageDialog(this, "Withdrawal amount must be greater than zero.");
            return;
        }

        // Query to get current balance
        String getBalanceQuery = "SELECT Balance FROM accountdetails WHERE Email = ?";
        try (PreparedStatement psGet = con.prepareStatement(getBalanceQuery)) {
            psGet.setString(1, loggedInEmail);  // Use the logged-in email to fetch balance

            ResultSet rs = psGet.executeQuery();
            if (rs.next()) {
                double currentBalance = rs.getDouble("Balance");
                
                // Check if the user has sufficient balance for the withdrawal
                if (withdrawAmount > currentBalance) {
                    JOptionPane.showMessageDialog(this, "Insufficient balance for this withdrawal.");
                    return;
                }

                // Calculate the new balance after withdrawal
                double newBalance = currentBalance - withdrawAmount;

                // Update balance in the database
                String updateBalanceQuery = "UPDATE accountdetails SET Balance = ? WHERE Email = ?";
                try (PreparedStatement psUpdate = con.prepareStatement(updateBalanceQuery)) {
                    psUpdate.setDouble(1, newBalance);  // Set the new balance
                    psUpdate.setString(2, loggedInEmail);  // Use the logged-in email

                    psUpdate.executeUpdate();  // Execute the update query

                    // Update the balance label on this panel
                    lbl_Balance.setText(String.format("%.2f", newBalance));
                    txt_Withdraw.setText("");  // Clear the withdrawal text field

                    // Optionally, update the balance on other panels as well
                    lbl_WBalance.setText(String.format("%.2f", newBalance));  // Update the second panel's balance
                    lbl_DBalance.setText(String.format("%.2f", newBalance));  // Update the third panel's balance

                    // Notify the user that the withdrawal was successful
                    JOptionPane.showMessageDialog(this, "Withdrawal successful! New Balance: " + newBalance);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Account not found.");
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage());
    }
    }//GEN-LAST:event_btn_WithdrawActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(LoggedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(LoggedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(LoggedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(LoggedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            // Replace "user@example.com" with an actual email for testing
            new LoggedPage("user@example.com").setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DEPOSITPanel;
    private javax.swing.JPanel Head;
    private javax.swing.JPanel WITHDRAWPanel;
    private javax.swing.JPanel WelcomePanel;
    private javax.swing.JButton btn_Deposit;
    private javax.swing.JButton btn_Withdraw;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JLabel lbl_Balance;
    public static javax.swing.JLabel lbl_DBalance;
    public static javax.swing.JLabel lbl_Name;
    public static javax.swing.JLabel lbl_WBalance;
    private javax.swing.JTextField txt_Deposit;
    private javax.swing.JTextField txt_Withdraw;
    // End of variables declaration//GEN-END:variables
}
