/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bank.management.system.pkg1;

import java.awt.Color;
import java.sql.Connection;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
//DATE
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
//LOGIN
import java.sql.ResultSet;
/**
 *
 * @author DAEZ
 */
public class MenuForm extends javax.swing.JFrame {

    /**
     * Creates new form MenuForm
     */
    public MenuForm() {
        initComponents();
        try {
            Connection();
        } catch (SQLException ex) {
            Logger.getLogger(MenuForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // Initialize the email text field with placeholder text
    LogEmail.setText("Enter Email");
    LogEmail.setForeground(Color.GRAY);  // Set text color to gray for placeholder

    // Initialize the password text field with placeholder text
    LogPassword.setText("Enter Password");
    LogPassword.setEchoChar((char) 0);  // Disable password masking for placeholder
    LogPassword.setForeground(Color.GRAY);  // Set text color to gray for placeholder

    // Add focus listener for the Email field
    LogEmail.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (LogEmail.getText().equals("Enter Email")) {
                LogEmail.setText(""); // Clear placeholder text
                LogEmail.setForeground(Color.BLACK); // Change text color to black
            }
        }

        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (LogEmail.getText().isEmpty()) {
                LogEmail.setText("Enter Email"); // Restore placeholder text
                LogEmail.setForeground(Color.GRAY); // Set text color to gray
            }
        }
    });

    // Add focus listener for the Password field
    LogPassword.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (new String(LogPassword.getPassword()).equals("Enter Password")) {
                LogPassword.setText(""); // Clear placeholder text
                LogPassword.setEchoChar('●'); // Enable password masking
                LogPassword.setForeground(Color.BLACK); // Change text color to black
            }
        }

        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (new String(LogPassword.getPassword()).isEmpty()) {
                LogPassword.setText("Enter Password"); // Restore placeholder text
                LogPassword.setEchoChar((char) 0); // Disable password masking for placeholder
                LogPassword.setForeground(Color.GRAY); // Set text color to gray
            }
        }
    });
        
    }
    
    Connection con;
    Statement st;
    
    private static final String DbName = "bangko";
    private static final String DbDriver = "com.mysql.cj.jdbc.Driver";
    private static final String DbUrl = "jdbc:mysql://localhost:3306/"+DbName;
    private static final String DbUsername = "root";
    private static final String DbPassword = "";
    
    public void Connection() throws SQLException{
        try {
            Class.forName(DbDriver);
            con = (Connection) DriverManager.getConnection(DbUrl,DbUsername,DbPassword);
            st = con.createStatement();
            if (con!= null){
                System.out.print("Connection Successful");
            }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuForm.class.getName()).log(Level.SEVERE, null, ex);
            
        }
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Head = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        AboutPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        LoginPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        LogEmail = new javax.swing.JTextField();
        LogPassword = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        SignUpPanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        SignUpButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ContactNumber = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        LastName = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        FirstName = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        BirthDate = new com.toedter.calendar.JDateChooser();
        Address = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        PIN = new javax.swing.JPasswordField();
        ConfirmPIN = new javax.swing.JPasswordField();
        ConfirmPassword = new javax.swing.JPasswordField();
        jLabel32 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Head.setBackground(java.awt.Color.white);
        Head.setPreferredSize(new java.awt.Dimension(1280, 95));
        Head.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setText("BANGKO");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        Head.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/management/system/pkg1/BANGKO 40x40.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        Head.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jButton4.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/management/system/pkg1/LoginButn.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        Head.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, -1, -1));

        jLabel16.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel16.setText("Home");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        Head.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 40, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/management/system/pkg1/icons8_close_window_25px_3.png"))); // NOI18N
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        Head.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, -1, -1));

        jPanel1.add(Head, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, -1));

        AboutPanel.setBackground(java.awt.Color.white);

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 72)); // NOI18N
        jLabel2.setText("BANGKO");

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 53)); // NOI18N
        jLabel3.setText("Welcome to");

        jScrollPane2.setBorder(null);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Bangko is a basic banking system developed using Java in NetBeans. The system was created by Villadarez, Generalao, and Satina as the final requirement for their subject, EL 201: Object-Oriented Programming.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jTextArea1.setCaretColor(java.awt.Color.white);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/management/system/pkg1/BANK BIG.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/management/system/pkg1/SignupButton.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AboutPanelLayout = new javax.swing.GroupLayout(AboutPanel);
        AboutPanel.setLayout(AboutPanelLayout);
        AboutPanelLayout.setHorizontalGroup(
            AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutPanelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(100, 100, 100)
                .addGroup(AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AboutPanelLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel5))
                    .addComponent(jLabel6)))
        );
        AboutPanelLayout.setVerticalGroup(
            AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutPanelLayout.createSequentialGroup()
                .addGroup(AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AboutPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AboutPanelLayout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jLabel5))
                            .addComponent(jLabel6)))
                    .addGroup(AboutPanelLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addGap(50, 50, 50))
        );

        jTabbedPane1.addTab("tab1", AboutPanel);

        LoginPanel.setBackground(java.awt.Color.white);

        jPanel5.setBackground(new java.awt.Color(254, 252, 249));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 330, 20));

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 330, 20));

        jLabel7.setFont(new java.awt.Font("Poppins SemiBold", 0, 30)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Login to your Account");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 380, 46));

        jLabel11.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/management/system/pkg1/icons8_lock_30px.png"))); // NOI18N
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        LogEmail.setBackground(new java.awt.Color(254, 252, 249));
        LogEmail.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        LogEmail.setBorder(null);
        LogEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogEmailActionPerformed(evt);
            }
        });
        jPanel5.add(LogEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 280, 42));

        LogPassword.setBackground(new java.awt.Color(254, 252, 249));
        LogPassword.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        LogPassword.setToolTipText("");
        LogPassword.setBorder(null);
        jPanel5.add(LogPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 280, 42));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/management/system/pkg1/icons8_user_30px.png"))); // NOI18N
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jButton1.setBackground(new java.awt.Color(252, 192, 62));
        jButton1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jButton1.setForeground(java.awt.Color.white);
        jButton1.setText("Login");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 160, 50));

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(252, 192, 62));
        jLabel8.setText("Sign up here");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel9.setText("Don't have an account?");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/management/system/pkg1/BANK BIG.png"))); // NOI18N

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel14))
                    .addComponent(jLabel15)))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginPanelLayout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jLabel14))
                            .addComponent(jLabel15)))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );

        jTabbedPane1.addTab("tab2", LoginPanel);

        SignUpPanel.setBackground(java.awt.Color.white);

        jPanel8.setBackground(new java.awt.Color(254, 252, 249));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jLabel22.setText("(PH number)");
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jLabel13.setFont(new java.awt.Font("Poppins SemiBold", 0, 30)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Create an Account");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 380, 46));

        SignUpButton.setBackground(new java.awt.Color(252, 192, 62));
        SignUpButton.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        SignUpButton.setForeground(java.awt.Color.white);
        SignUpButton.setText("Sign Up");
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });
        jPanel8.add(SignUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 160, 50));

        jLabel18.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(252, 192, 62));
        jLabel18.setText("Login here");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, -1, -1));

        jLabel19.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel19.setText("Already have an account?");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, -1, -1));

        ContactNumber.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        ContactNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactNumberActionPerformed(evt);
            }
        });
        jPanel8.add(ContactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 190, -1));

        jLabel23.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel23.setText("Last Name");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        LastName.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jPanel8.add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 190, -1));

        jLabel24.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel24.setText("First Name");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        FirstName.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jPanel8.add(FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 190, -1));

        jLabel25.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel25.setText("Email");
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        Email.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jPanel8.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 190, -1));

        jLabel26.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel26.setText("Confirm Password");
        jPanel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        jLabel27.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel27.setText("Password");
        jPanel8.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel28.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel28.setText("Date of Birth");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel29.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel29.setText("Confirm 4 Digit PIN");
        jPanel8.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        jLabel30.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel30.setText("4 Digit PIN");
        jPanel8.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));
        jPanel8.add(BirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 400, -1));

        Address.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jPanel8.add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 400, -1));

        jLabel31.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel31.setText("Address");
        jPanel8.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        Password.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jPanel8.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 190, -1));

        PIN.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jPanel8.add(PIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 190, -1));

        ConfirmPIN.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jPanel8.add(ConfirmPIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 190, -1));

        ConfirmPassword.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        jPanel8.add(ConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 190, -1));

        jLabel32.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel32.setText("Contact Number");
        jPanel8.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/management/system/pkg1/BANK BIG.png"))); // NOI18N

        javax.swing.GroupLayout SignUpPanelLayout = new javax.swing.GroupLayout(SignUpPanel);
        SignUpPanel.setLayout(SignUpPanelLayout);
        SignUpPanelLayout.setHorizontalGroup(
            SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpPanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SignUpPanelLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel20))
                    .addComponent(jLabel21)))
        );
        SignUpPanelLayout.setVerticalGroup(
            SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SignUpPanelLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel20))
                    .addComponent(jLabel21))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignUpPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", SignUpPanel);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogEmailActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        // TODO add your handling code here:
        
        if ("".equals(Email.getText()) || "".equals(Password.getText()) || "".equals(ConfirmPassword.getText()) 
    || "".equals(FirstName.getText()) || "".equals(LastName.getText()) || "".equals(PIN.getText()) 
    || "".equals(ConfirmPIN.getText()) || "".equals(ContactNumber.getText()) || "".equals(Address.getText()) 
    || BirthDate.getDate() == null) {
    JOptionPane.showMessageDialog(new JFrame(), "All fields are required");
} else {
    String email = Email.getText();
    String password = Password.getText();
    String confirmPassword = ConfirmPassword.getText(); // Get Confirm Password
    String firstname = FirstName.getText();
    String lastname = LastName.getText();
    String pin = PIN.getText();          // Get the PIN
    String confirmPin = ConfirmPIN.getText(); // Get Confirm PIN
    String contactnum = ContactNumber.getText();  // Get the contact number
    String address = Address.getText();
    
    // **Email Validation**
    if (!email.matches("^[\\w._%+-]+@[\\w.-]+\\.com$")) {
        JOptionPane.showMessageDialog(new JFrame(), "Invalid email format. Email must contain '@' and end with '.com'.");
        return; // Stop further execution if the email is invalid
    }
    
    // Check if Email Already Exists
        String emailCheckQuery = "SELECT * FROM accountdetails WHERE Email = ?";
        try (PreparedStatement psCheck = con.prepareStatement(emailCheckQuery)) {
            psCheck.setString(1, email);
            try (ResultSet rs = psCheck.executeQuery()) {
                if (rs.next()) {
                    JOptionPane.showMessageDialog(new JFrame(), "Email is already registered. Please use a different email.");
                    return; // Stop further execution
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(new JFrame(), "Error checking email: " + ex.getMessage());
            return;
        }

    // Validate that PIN is exactly 4 digits
    if (!pin.matches("\\d{4}")) { // Regex for 4-digit numeric PIN
        JOptionPane.showMessageDialog(new JFrame(), "PIN must be exactly 4 digits.");
        return; // Stop further execution if PIN is invalid
    }

    // Check if Password and Confirm Password match
    if (!password.equals(confirmPassword)) {
        JOptionPane.showMessageDialog(new JFrame(), "Password and Confirm Password must match.");
        return; // Stop further execution if passwords do not match
    }

    // Check if PIN and Confirm PIN match
    if (!pin.equals(confirmPin)) {
        JOptionPane.showMessageDialog(new JFrame(), "PIN and Confirm PIN must match.");
        return; // Stop further execution if PINs do not match
    }

    // Validate Contact Number: Must start with 09 and be exactly 11 digits
    if (!contactnum.matches("^09\\d{9}$")) { // Regex for "09" followed by 9 digits
        JOptionPane.showMessageDialog(new JFrame(), "Contact number must start with '09' and be exactly 11 digits.");
        return; // Stop further execution if contact number is invalid
    }

    // Retrieve the selected date from JDateChooser and convert it to java.sql.Date
    Date selectedDate = BirthDate.getDate();
    java.sql.Date birthdate = null;
    if (selectedDate != null) {
        birthdate = new java.sql.Date(selectedDate.getTime()); // Convert java.util.Date to java.sql.Date

        // Calculate the age based on the selected birthdate
        LocalDate birthLocalDate = selectedDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate currentDate = LocalDate.now();
        int age = Period.between(birthLocalDate, currentDate).getYears();

        // Check if age is below 18
        if (age < 18) {
            JOptionPane.showMessageDialog(new JFrame(), "You must be at least 18 years old to register.");
            return; // Stop further execution
        }
    }

    // Adjust the column names to match your table structure
    String querySignUp = "INSERT INTO accountdetails (Email, Password, Firstname, Lastname, Contactnum, Birthdate, Address, Balance, PIN) "
                    + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
    try (PreparedStatement ps = con.prepareStatement(querySignUp)) {
        ps.setString(1, email);      // Set email
        ps.setString(2, password);   // Set password
        ps.setString(3, firstname);  // Set firstname
        ps.setString(4, lastname);   // Set lastname
        ps.setString(5, contactnum); // Set contact number
        if (birthdate != null) {
            ps.setDate(6, birthdate); // Set birthdate as java.sql.Date
        } else {
            // Handle the case where birthdate is null (if necessary)
            ps.setNull(6, java.sql.Types.DATE);
        }
        ps.setString(7, address);    // Set address
        ps.setDouble(8, 0.0);        // Set Balance to 0.0 initially
        ps.setString(9, pin);        // Set PIN

        ps.executeUpdate(); // Execute the query
        JOptionPane.showMessageDialog(new JFrame(), "Registered Successfully");
        
        // Clear all input fields
        Email.setText("");
        Password.setText("");
        ConfirmPassword.setText("");
        FirstName.setText("");
        LastName.setText("");
        PIN.setText("");
        ConfirmPIN.setText("");
        ContactNumber.setText("");
        Address.setText("");
        BirthDate.setDate(null); // Reset the JDateChooser field
        
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(new JFrame(), "Registration failed: " + ex.getMessage());
    }
}
        
        
    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void ContactNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactNumberActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ContactNumberActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          String email = LogEmail.getText();
    String password = LogPassword.getText();

    if ("".equals(email) || "".equals(password)) {
        JOptionPane.showMessageDialog(this, "Email and Password are required!");
    } else {
        // Check if the entered email and password exist in the database
        String queryLogin = "SELECT * FROM accountdetails WHERE Email = ? AND Password = ?";
        
        try (PreparedStatement ps = con.prepareStatement(queryLogin)) {
            // Set the parameters for the prepared statement
            ps.setString(1, email);  // Set email parameter
            ps.setString(2, password);  // Set password parameter

            // Execute the query
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {  // If there is a matching row
                    // Successfully logged in, proceed to LoggedPage JFrame
                    JOptionPane.showMessageDialog(this, "Login successful!");
                    
                    LoggedPage loggedPage = new LoggedPage(email);
                    loggedPage.setVisible(true);
                    this.dispose(); // Close the login form
                    String name = rs.getString("Firstname");
                    String balance = rs.getString("Balance");
                    LoggedPage.lbl_Name.setText(name);
                    LoggedPage.lbl_Balance.setText(balance);
                    LoggedPage.lbl_DBalance.setText(balance);
                    LoggedPage.lbl_WBalance.setText(balance);
                } else {
                    // Incorrect email or password
                    JOptionPane.showMessageDialog(this, "Invalid Email or Password!");
                    
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error executing query: " + ex.getMessage());
                ex.printStackTrace();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database connection error: " + ex.getMessage());
            ex.printStackTrace();
        }
    }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        // Display a confirmation dialog when the label is clicked
    int response = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to exit?", 
            "Exit Confirmation", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE);
    
    // If the user selects "Yes," exit the application
    if (response == JOptionPane.YES_OPTION) {
        System.exit(0); // Close the application
    }
    }//GEN-LAST:event_jLabel17MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AboutPanel;
    private javax.swing.JTextField Address;
    private com.toedter.calendar.JDateChooser BirthDate;
    private javax.swing.JPasswordField ConfirmPIN;
    private javax.swing.JPasswordField ConfirmPassword;
    private javax.swing.JTextField ContactNumber;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField FirstName;
    private javax.swing.JPanel Head;
    private javax.swing.JTextField LastName;
    private javax.swing.JTextField LogEmail;
    private javax.swing.JPasswordField LogPassword;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JPasswordField PIN;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JPanel SignUpPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
